config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  get 'user_sessions/new'
  get 'user_sessions/create'
  # Defines the root path route ("/")
  root 'users#new'
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new,  :block, :unblock, :delete, :create]


  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'
  get '/logout' => 'user_sessions#destroy'


  delete '/users/delete', to: 'users#delete'
  put '/users/delete', to: 'users#delete'

  put '/users/block', to: 'users#block'
  delete '/users/block', to: 'users#block'

  put '/users/unblock', to: 'users#unblock'
  delete '/users/unblock', to: 'users#unblock'
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password :password
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  
    def current_user
      @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
    end
end
  

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.find_by(email: params[:user][:email], status: 'Active')
    
        if @user&.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          @user.update!(last_login: Time.current)
          redirect_to users_path
        else
          flash[:alert] = "Invalid email or password."
          redirect_to new_user_session_path
        end
      end
    
      def destroy
        session[:user_id] = nil
        flash[:notice] = "Successfully logged out."
        redirect_to root_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
      if current_user.blank?
          render plain: '401 Unauthorized.', status: :unauthorized
      end
      @users = User.all
    end
  
    def new
      @user = User.new
    end
  
    def block
      selected_user_ids = params[:user_ids]
  
      puts "Selected User IDs: #{params.inspect}"
      if params.has_key?(:unblock)
       
        unblock(params)

      elsif params.has_key?(:remove)
  
        delete(params)
      else
        selected_user_ids = params[:user_ids]
        puts "Selected User IDs: #{selected_user_ids.inspect}"
        if selected_user_ids.present?
        User.where(id: selected_user_ids).update_all(status: 'Blocked')
        flash[:notice] = "Selected users are blocked successfully."
          else
            flash[:alert] = "Please select at least one user to block."
        end
      end
      if current_user.blank?
          redirect_to logout_path
          return
      end
    redirect_to users_path
      

    end
  
    def unblock(params)
  
      selected_user_ids = params[:user_ids]
      puts "Selected User IDs: #{selected_user_ids.inspect}"
      if selected_user_ids.present?
        User.where(id: selected_user_ids).update_all(status: 'Active')
        flash[:notice] = "Selected users are unblocked successfully"
      else
        flash[:alert] = "Please select at least one user to unblock"
      end
    
    end
  
    def delete(params)
      selected_user_ids = params[:user_ids]
      puts "Selected User IDs: #{selected_user_ids.inspect}"
      if selected_user_ids.present?
        User.where(id: selected_user_ids).destroy_all()
        flash[:notice] = "Selected users are deleted successfully"
      else
        flash[:alert] = "Please select at least one user to delete"
      end
    end
  
    def create
      @user = User.new(user_params)
      @user.status = "Active"
      @user.registration_time = Time.current
      @user.last_login = Time.current
      if @user.save
        flash[:notice] = "User has been created successfully!"
        session[:user_id] = @user.id 
        redirect_to user_sessions_new_path
  
      else
        flash[:alert] = "User has not been created!"
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Userspanel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/create,html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
    <h1>Login page</h1>
  
    <%= form_with model: @user, url: user_sessions_path do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
  
      <br>
      <p class="text-center">
        <%= f.submit 'Login', class: "btn btn-primary" %>
      </p>
  
      <p class="text-center"> Don't have an account? </p>
      <p class="text-center">
        <%= link_to 'Sign Up', new_user_path %>
      </p>
    <% end %>
</div>
  

app/views/users/block.html.erb
<h1>Users#block</h1>
<p>Find me in app/views/users/block.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<nav class="navbar navbar-light bg-light container">  
  <a href=<%= users_path %> class="navbar-brand">
    Users Panel
  </a>
  <span class="navbar-nav">
    <h6>Welcome, <br> <%= current_user.name %></h6>
    <%= link_to "Log Out", logout_path , method: "delete"%>
  </span>
</nav>

<div class="container">
  <div class="row mt-5 mb-2">  
    <div class="col-md-12">  
      <%= form_tag(users_block_path, method: :put, id: 'block_form') do %>
      <%= button_tag(type: 'submit',  :name => 'block',class: "btn btn-warning action-buttonn",form: 'block_form' ) do %>
      <i class="bi bi-lock-fill"></i> Block
      <% end %>&nbsp;
      <%= button_tag(type: 'submit',  :name => 'unblock',class: "btn btn-primary action-button", form: 'block_form' ) do %>
      <i class="bi bi-unlock-fill"></i> Unblock
      <% end %>&nbsp;
      <%= button_tag(type: 'submit',  :name => 'remove',class: "btn btn-danger action-button", form: 'block_form' ) do %>
      <i class="bi bi-trash-fill"></i> Delete
      <% end %>
    </div>
  </div>

  <hr>

  <table class="table table-hover">  
    <thead>
      <tr>
        <th><input type="checkbox" id="select_all"></th>
        <th>Name</th>
        <th>E-mail</th>
        <th>Last login time</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= check_box_tag 'user_ids[]', user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.last_login %></td>
          <td><%= user.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('select_all').addEventListener('change', function () {
      var checkboxes = document.querySelectorAll('tbody input[type="checkbox"]');
      checkboxes.forEach(function (checkbox) {
        checkbox.checked = this.checked;
      }, this);
    });

    document.querySelectorAll('.action-button').forEach(function (button) {
      button.addEventListener('click', function () {
        var formId = this.dataset.formId;
        document.getElementById(formId).submit();
      });
    });
  });

</script>

app/views/users/new.html.erb
<div class="container">
    <h1>Sign Up</h1>
  
    <%= form_with model: @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="mb-3">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
  
      <div class="mb-3">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
  
      <div class="mb-3">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: "form-control" %>
      </div>
  
      <p>
        <%= f.submit "Sign Up", class: "btn btn-primary" %>
      </p>
  
      <p> Already have an account? </p>
      <%= link_to 'Login', new_user_session_path %><br>
    <% end %>
</div>
  

app/views/users/unblock.html.erb
<h1>Users#unblock</h1>
<p>Find me in app/views/users/unblock.html.erb</p>